"""Add DEPT, EMP, BONUS, SALGRADE tables

Revision ID: d929e9d883d5
Revises: 609a204b6d4c
Create Date: 2025-05-14 19:29:10.511812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd929e9d883d5'
down_revision = '609a204b6d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ename', sa.String(length=10), nullable=True),
    sa.Column('job', sa.String(length=9), nullable=True),
    sa.Column('sal', sa.Numeric(), nullable=True),
    sa.Column('comm', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dept',
    sa.Column('deptno', sa.Integer(), nullable=False),
    sa.Column('dname', sa.String(length=14), nullable=True),
    sa.Column('loc', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('deptno')
    )
    op.create_table('salgrade',
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('losal', sa.Numeric(), nullable=True),
    sa.Column('hisal', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('grade')
    )
    op.create_table('emp',
    sa.Column('empno', sa.Integer(), nullable=False),
    sa.Column('ename', sa.String(length=10), nullable=True),
    sa.Column('job', sa.String(length=9), nullable=True),
    sa.Column('mgr', sa.Integer(), nullable=True),
    sa.Column('hiredate', sa.Date(), nullable=True),
    sa.Column('sal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('comm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('deptno', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deptno'], ['dept.deptno'], ),
    sa.PrimaryKeyConstraint('empno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp')
    op.drop_table('salgrade')
    op.drop_table('dept')
    op.drop_table('bonus')
    # ### end Alembic commands ###
