DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER(10) PRIMARY KEY,
    COMPANY_NAME    VARCHAR2(100) NOT NULL,
    CONTACT_NAME    VARCHAR2(50),
    CONTACT_TITLE   VARCHAR2(50),
    PHONE           VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    ADDRESS         VARCHAR2(200),
    CITY            VARCHAR2(50),
    COUNTRY         VARCHAR2(50),
    CREDIT_LIMIT    NUMBER(12,2),
    CREDIT_RATING   VARCHAR2(10) CHECK (CREDIT_RATING IN ('A', 'B', 'C', 'D')),
    CREATED_DATE    DATE DEFAULT SYSDATE,
    LAST_MODIFIED   DATE DEFAULT SYSDATE,
    STATUS          VARCHAR2(10) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    INDUSTRY        VARCHAR2(50),
    ANNUAL_REVENUE  NUMBER(15,2),
    EMPLOYEE_COUNT  NUMBER(10)
);

-- Create sequence
DROP SEQUENCE seq_customer_id;
CREATE SEQUENCE seq_customer_id START WITH 1000 INCREMENT BY 1;
